### ISSUE TITLE
redundant call of "self.test_gen.build_prompt(failed_test_runs, language, test_framework, coverage_report)" inside of CoverAgent.init()

### ISSUE THREAD

**Issue by Cachet23** [qodo-ai/qodo-cover#245]
Hey, 
while trying to find out about the way the system functions I stumbled upon a function call where I can't see the reason for the call.
Why call test_gen.build_prompt(x,x,x,x) inside of init(), when we do not assign the return value of build_prompt() to any variable?

`        
# Run initial test suite analysis
        self.test_validator.initial_test_suite_analysis()
        failed_test_runs, language, test_framework, coverage_report = self.test_validator.get_coverage()
        self.test_gen.build_prompt(failed_test_runs, language, test_framework, coverage_report) <<== here the return of the function fiddles?

        return failed_test_runs, language, test_framework, coverage_report
`
        
        
I thought:
maybe we call the build_prompt() to initialize the PromptBuilder..However straight in the beginning of run_test_gen() we call generate_tests() and inside of generate_tests() we call build.prompt(), but this time we assign it a variable. So I assume initializing the PromptBuilder is not the reason for calling this method.

sadly I'm currently unsure what the poetry equivalent to "pip install -e" is, so I could test If everything still works after removing this one line from init() method.

I'm super happy about any advice or answer :) Feel free to close this as soon as you want!

Best wishes <3

**Comment by EmbeddedDevops1** [comment]
@Cachet23 thanks for filing this issue. This was a leftover line of code from a refactoring job. Nice catch. Thanks so much for the contribution. I am fixing it now.
